version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: cliente-db
    environment:
      - POSTGRES_DB=cliente
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5436:5432

  app:
    depends_on:
      - postgres
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5436/cliente
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
